  texts:
  - '&eqwqqwqqwqqwqqwq'
  - '&eqwqqwqqwqqwqqwq'
  - '&eqwqqwqqwqqwqqwq'
  - '&eqwqqwqqwqqwqqwq'
  - '&eqwqqwqqwqqwqqwq'
  - '&eqwqqwqqwqqwqqwq'
  - '&e&eq&ewqqwqqwqqwqqwq'
  - '&eq&6w&eqqwqqwqqwqqwq'
  - '&eqw&eq&eqwqqwqqwqqwq'
  - '&eqwq&6q&ewqqwqqwqqwq'
  - '&eqwqq&ew&eqqwqqwqqwq'
  - '&eqwqqw&6q&eqwqqwqqwq'
  - '&eqwqqwq&eq&ewqqwqqwq'
  - '&eqwqqwqq&6w&eqqwqqwq'
  - '&eqwqqwqqw&eq&eqwqqwq'
  - '&eqwqqwqqwq&6q&ewqqwq'
  - '&eqwqqwqqwqq&ew&eqqwq'
  - '&eqwqqwqqwqqw&6q&eqwq'
  - '&eqwqqwqqwqqwq&eq&ewq'
  - '&eqwqqwqqwqqwqq&6w&eq'
  - '&eqwqqwqqwqqwqqw&eq&e'
  - '&eqwqqwqqwqqwqqwq'
  - '&eqwqqwqqwqqwqqwq'
  - '&eqwqqwqqwqqwqqwq'
  - '&eqwqqwqqwqqwqqwq'
  - '&eqwqqwqqwqqwqqwq'
  - '&eqwqqwqqwqqwqqwq'